# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='blog/'),
        ),
    ]
